@selectionBackground = lighten(if(@accentColor, @accentColor, @accentBaseColor),42%)
TabbedPane.focusColor = mix(@accentSelectionBackground,$TabbedPane.background,10%)
TextArea.inactiveBackground = tint(@background,50%)